<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bank_detail extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bank_detail_model');
    } 

    /*
     * Listing of bank_details
     */
    function index()
    {
        $data['bank_details'] = $this->Bank_detail_model->get_all_bank_details();
        
        $data['_view'] = 'bank_detail/index';
        $this->load->view('layouts/main',$data);
    }  

    /*
     * Editing a bank_detail
     */
    function edit($bank_id)
    {   
        // check if the bank_detail exists before trying to edit it
        $data['bank_detail'] = $this->Bank_detail_model->get_bank_detail($bank_id);
        
        if(isset($data['bank_detail']['bank_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'user_id' => $this->input->post('user_id'),
					'holder_name' => $this->input->post('holder_name'),
					'bank_name' => $this->input->post('bank_name'),
					'ifsc' => $this->input->post('ifsc'),
					'account_number' => $this->input->post('account_number'),
					'pan_number' => $this->input->post('pan_number'),
                );

                $this->Bank_detail_model->update_bank_detail($bank_id,$params);            
                redirect('bank_detail/index');
            }
            else
            {
                $data['_view'] = 'bank_detail/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The bank_detail you are trying to edit does not exist.');
    }
}
