<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Company_rating extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Company_rating_model');
    }
}
