<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
class Company extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Company_model');
    } 

    /*
     * Listing of companies
     */
    function index()
    {
        $data['companies'] = $this->Company_model->get_all_companies();
        
        $data['_view'] = 'company/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new company
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'status' => '1',
				'password' => $this->input->post('password'),
				'rating' => '0',
				'type' => $this->input->post('type'),
				'name' => $this->input->post('name'),
				'email' => $this->input->post('email'),
				'phone' => $this->input->post('phone'),
				'enrolled' => '0',
				'timestamp' => '0',
				'logo' => $this->input->post('logo'),
				'about' => $this->input->post('about'),
            );
            
            $company_id = $this->Company_model->add_company($params);
            redirect('company/index');
        }
        else
        {            
            $data['_view'] = 'company/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a company
     */
    function edit($company_id)
    {   
        // check if the company exists before trying to edit it
        $data['company'] = $this->Company_model->get_company($company_id);
        
        if(isset($data['company']['company_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'status' => $this->input->post('status'),
					'password' => $this->input->post('password'),
					'rating' => $this->input->post('rating'),
					'type' => $this->input->post('type'),
					'name' => $this->input->post('name'),
					'email' => $this->input->post('email'),
					'phone' => $this->input->post('phone'),
					'enrolled' => $this->input->post('enrolled'),
					'timestamp' => $this->input->post('timestamp'),
					'logo' => $this->input->post('logo'),
					'about' => $this->input->post('about'),
                );

                $this->Company_model->update_company($company_id,$params);            
                redirect('company/index');
            }
            else
            {
                $data['_view'] = 'company/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The company you are trying to edit does not exist.');
    } 

    /*
     * Deleting company
     */
    function remove($company_id)
    {
        $company = $this->Company_model->get_company($company_id);

        // check if the company exists before trying to delete it
        if(isset($company['company_id']))
        {
            $this->Company_model->delete_company($company_id);
            redirect('company/index');
        }
        else
            show_error('The company you are trying to delete does not exist.');
    }
    
}
