<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_company extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_company_model');
    } 

    /*
     * Listing of user_companies
     */
    function index()
    {
        $data['user_companies'] = $this->User_company_model->get_all_user_companies();
        
        $data['_view'] = 'user_company/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new user_company
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'company_id' => $this->input->post('company_id'),
				'user_id' => $this->input->post('user_id'),
				'timestamp' => $this->input->post('timestamp'),
            );
            
            $user_company_id = $this->User_company_model->add_user_company($params);
            redirect('user_company/index');
        }
        else
        {            
            $data['_view'] = 'user_company/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a user_company
     */
    function edit($user_companies_id)
    {   
        // check if the user_company exists before trying to edit it
        $data['user_company'] = $this->User_company_model->get_user_company($user_companies_id);
        
        if(isset($data['user_company']['user_companies_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'company_id' => $this->input->post('company_id'),
					'user_id' => $this->input->post('user_id'),
					'timestamp' => $this->input->post('timestamp'),
                );

                $this->User_company_model->update_user_company($user_companies_id,$params);            
                redirect('user_company/index');
            }
            else
            {
                $data['_view'] = 'user_company/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user_company you are trying to edit does not exist.');
    } 

    /*
     * Deleting user_company
     */
    function remove($user_companies_id)
    {
        $user_company = $this->User_company_model->get_user_company($user_companies_id);

        // check if the user_company exists before trying to delete it
        if(isset($user_company['user_companies_id']))
        {
            $this->User_company_model->delete_user_company($user_companies_id);
            redirect('user_company/index');
        }
        else
            show_error('The user_company you are trying to delete does not exist.');
    }
    
}
